# Generated by Django 3.1.5 on 2021-02-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizen_id', models.PositiveIntegerField(verbose_name='id гражданина')),
                ('import_id', models.PositiveIntegerField(verbose_name='id импорт')),
                ('town', models.CharField(max_length=256, verbose_name='Название города')),
                ('street', models.CharField(max_length=256, verbose_name='Название улицы')),
                ('building', models.CharField(max_length=256, verbose_name='Номер дома, корпус, строение')),
                ('apartment', models.PositiveIntegerField(verbose_name='Номер квартиры')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], max_length=6, verbose_name='Пол')),
                ('relatives', models.ManyToManyField(related_name='_citizen_relatives_+', to='task_app.Citizen', verbose_name='Ближайшие родственники')),
            ],
        ),
    ]
