# Generated by Django 3.1.5 on 2021-02-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
