# Generated by Django 3.1.5 on 2021-02-03 04:14

from django.db import migrations, models
import task_app.tools


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20210202_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='birth_date',
            field=models.DateField(validators=[task_app.tools.validate_date], verbose_name='Дата рождения'),
        ),
    ]
